### ISSUE TITLE
responsive issues with the footer

### ISSUE THREAD

**Issue by andrewmcodes** [bt-rb/bridgetown-theme-bootstrap-blog#1]
### Version

58a667b2900c80d62c82717e6a4ac91543c14e15

### Description

The footer needs some touch ups on small screens. See screenshot. 

<details open>
<summary>Screenshots</summary>
<br>

![image](https://user-images.githubusercontent.com/18423853/103405433-18fc6780-4b25-11eb-82d4-75bdbd0882db.png)
</details>

### Steps to reproduce

View the footer on a small screen. 

### What is Expected?

It doesn't look janky. 

### What is actually happening?

It looks janky. Should just need some responsive bootstrap classes.

**Comment by andrewmcodes** [comment]
@cjilbert504 Can you tackle this? Lmk if you need anything.

**Comment by cjilbert504** [comment]
@andrewmcodes Yep I can get on this.

**Comment by cjilbert504** [comment]
I somewhat un-jankified this [here](https://github.com/bt-rb/bridgetown-theme-bootstrap-blog/pull/5) but def needs a bit more touch up on mobile view. The github icon is basically touching the button underneath it. Just putting this comment out there so I can reminder myself of it later on unless you get to it first that is, @andrewmcodes .

**Comment by cjilbert504** [comment]
@andrewmcodes this also can probably be closed. I think this was also handled in the changes that were made when we paired the other night.
